/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as context from "../context"
import { Board } from "../api/board"
import { Game } from "../api/game"
import { Node } from "../api/node"
import { Player } from "../api/player"
import { ExpectedAction } from "../api/action"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  ActionType: "DropPiece" | "Heartbeat" | "PlayerJoin"
}

export interface NexusGenRootTypes {
  Board: Board;
  BoardColumn: { // root type
    pieces: NexusGenRootTypes['BoardPiece'][]; // [BoardPiece!]!
  }
  BoardPiece: { // root type
    playerId?: string | null; // String
  }
  ExpectedAction: ExpectedAction;
  Game: Game;
  GameAndPlayer: { // root type
    game: NexusGenRootTypes['Game']; // Game!
    player: NexusGenRootTypes['Player']; // Player!
  }
  GameEvent: { // root type
    changedNodes: NexusGenRootTypes['Node'][]; // [Node!]!
  }
  Mutation: {};
  Player: Player;
  Query: {};
  Subscription: {};
  Node: Node;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  ActionType: NexusGenEnums['ActionType'];
}

export interface NexusGenFieldTypes {
  Board: { // field return type
    columns: NexusGenRootTypes['BoardColumn'][]; // [BoardColumn!]!
    id: string; // ID!
  }
  BoardColumn: { // field return type
    pieces: NexusGenRootTypes['BoardPiece'][]; // [BoardPiece!]!
  }
  BoardPiece: { // field return type
    playerId: string | null; // String
  }
  ExpectedAction: { // field return type
    actorId: string | null; // String
    type: NexusGenEnums['ActionType'] | null; // ActionType
  }
  Game: { // field return type
    board: NexusGenRootTypes['Board']; // Board!
    expectedActions: NexusGenRootTypes['ExpectedAction'][]; // [ExpectedAction!]!
    id: string; // ID!
    name: string; // String!
    numPlayers: number; // Int!
    players: NexusGenRootTypes['Player'][]; // [Player!]!
  }
  GameAndPlayer: { // field return type
    game: NexusGenRootTypes['Game']; // Game!
    player: NexusGenRootTypes['Player']; // Player!
  }
  GameEvent: { // field return type
    changedNodes: NexusGenRootTypes['Node'][]; // [Node!]!
  }
  Mutation: { // field return type
    createGame: NexusGenRootTypes['Game']; // Game!
    dropPiece: NexusGenRootTypes['Board']; // Board!
    heartbeat: NexusGenRootTypes['Game']; // Game!
    joinGameAsPlayer: NexusGenRootTypes['GameAndPlayer']; // GameAndPlayer!
  }
  Player: { // field return type
    id: string; // ID!
    isConnected: boolean; // Boolean!
    name: string; // String!
  }
  Query: { // field return type
    game: NexusGenRootTypes['Game']; // Game!
  }
  Subscription: { // field return type
    gameEvents: NexusGenRootTypes['GameEvent']; // GameEvent!
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createGame: { // args
      name?: string | null; // String
    }
    dropPiece: { // args
      column: number; // Int!
      gameId: string; // ID!
      playerId: string; // ID!
    }
    heartbeat: { // args
      gameId: string; // ID!
      playerId?: string | null; // ID
    }
    joinGameAsPlayer: { // args
      gameId: string; // ID!
      name: string; // String!
    }
  }
  Query: {
    game: { // args
      id: string; // ID!
    }
  }
  Subscription: {
    gameEvents: { // args
      gameId: string; // ID!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
  Node: "Game" | "Board" | "Player"
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Board" | "BoardColumn" | "BoardPiece" | "ExpectedAction" | "Game" | "GameAndPlayer" | "GameEvent" | "Mutation" | "Player" | "Query" | "Subscription";

export type NexusGenInputNames = never;

export type NexusGenEnumNames = "ActionType";

export type NexusGenInterfaceNames = "Node";

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}