/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as context from "../context"
import { Game } from "../models/game"
import { Player } from "../models/player"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenRootTypes {
  Action: { // root type
    type: string; // String!
  }
  ActionSubscriptionPayload: { // root type
    action: NexusGenRootTypes['Action']; // Action!
    game: NexusGenRootTypes['Game']; // Game!
  }
  Game: Game;
  Mutation: {};
  Player: Player;
  Query: {};
  Subscription: {};
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
}

export interface NexusGenFieldTypes {
  Action: { // field return type
    type: string; // String!
  }
  ActionSubscriptionPayload: { // field return type
    action: NexusGenRootTypes['Action']; // Action!
    game: NexusGenRootTypes['Game']; // Game!
  }
  Game: { // field return type
    id: string; // ID!
    name: string; // String!
    numPlayers: number; // Int!
    players: NexusGenRootTypes['Player'][]; // [Player!]!
  }
  Mutation: { // field return type
    addPlayerToGame: NexusGenRootTypes['Player']; // Player!
    createGame: NexusGenRootTypes['Game']; // Game!
  }
  Player: { // field return type
    name: string; // String!
  }
  Query: { // field return type
    game: NexusGenRootTypes['Game']; // Game!
  }
  Subscription: { // field return type
    actions: NexusGenRootTypes['ActionSubscriptionPayload']; // ActionSubscriptionPayload!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addPlayerToGame: { // args
      gameId: string; // ID!
      name: string; // String!
    }
    createGame: { // args
      name?: string | null; // String
      numPlayers: number; // Int!
    }
  }
  Query: {
    game: { // args
      id: string; // ID!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Action" | "ActionSubscriptionPayload" | "Game" | "Mutation" | "Player" | "Query" | "Subscription";

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}